name: Terraform Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: infra

      - name: Terraform Plan (Non-Main Branch)
        if: github.ref != 'refs/heads/main'
        run: terraform plan
        working-directory: infra

      - name: Terraform Apply (Main Branch)
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
        working-directory: infra